CREATE TABLE `students` (
	`id` INT NULL,
	`first_name` VARCHAR(50) NULL DEFAULT NULL,
	`last_name` VARCHAR(50) NULL DEFAULT NULL,
	`age` INT NULL DEFAULT NULL,
	`grade` DOUBLE NULL DEFAULT NULL
)
COLLATE='utf8mb4_0900_ai_ci'
;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='softuni';
SHOW TABLE STATUS FROM `softuni`;
SHOW FUNCTION STATUS WHERE `Db`='softuni';
SHOW PROCEDURE STATUS WHERE `Db`='softuni';
SHOW TRIGGERS FROM `softuni`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='softuni';